
DEVICE = "cuda"
TRAIN_DIR = "train directory"
TEST_DIR = "test directory"
BATCH_SIZE = 16
LEARNING_RATE_GEN = 0.0001
LEARNING_RATE_DISC = 0.0001
LAMBDA_IDENTITY = 1
LAMBDA_FREQS = 10
LAMBDA_CYCLE = 10
NUM_WORKERS = 12
NUM_EPOCHS= 3000
CRITIC_ITERATIONS= 10
LAMBDA_GP = 10